name: Upload to S3

on: [pull_request]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ sAKIATBCXQYSNHBINY3BN  }}
          aws_secret_access_key: ${{ 56yWFgJiGWbsosOUj5tznkNd2FzABo11ncv6uEn/}}
          aws_bucket: ${{ app1-2042 }}
          source_dir: 'test'
