  name: Upload S3
  uses: shallwefootball/upload-s3-action@v1.1.1
  with:
    # aws key id
    aws_key_id: AKIATBCXQYSNIFM6UXYN
    # aws secret access key
    aws_secret_access_key: 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
    # aws bucket name
    aws_bucket: app1-2042
    # directory to upload
    source_dir: test
    # destination directory for upload
    destination_dir: # optional, default is /
